### ISSUE TITLE
[ERROR] Missing 'microsoft-scripting-chakra-instrumentationevents.h'

### ISSUE THREAD

**Issue by VitaliyMubarakov** [chakra-core/ChakraCore#6923] opened 2023-06-11 14:47 UTC
## System
Windows 10
Node v17.3.0.
NPM 8.5.0
Cmake 3.22.1

## Log

```
Build started...
1>------ Build started: Project: Chakra.SCACore, Configuration: Debug x64 ------
2>------ Build started: Project: Chakra.ICU.Stubdata, Configuration: Debug x64 ------
3>------ Build started: Project: Chakra.ICU.i18n, Configuration: Debug x64 ------
4>------ Build started: Project: Chakra.ICU.Data, Configuration: Debug x64 ------
5>------ Build started: Project: Chakra.ICU.Common, Configuration: Debug x64 ------
6>------ Build started: Project: wabt, Configuration: Debug x64 ------
7>------ Skipped Build: Project: pal, Configuration: Debug x64 ------
7>Project not selected to build for this solution configuration 
8>------ Build started: Project: CoreManifests, Configuration: Debug x64 ------
9>------ Build started: Project: Chakra.JITIDL, Configuration: Debug x64 ------
6>wabtapi.cc
9>midl : command line warning MIDL1007: switch specified more than once on command line : target
9>64 bit Processing C:\Programs\vcpkg\buildtrees\chakracore\x64-windows-rel\x64-windows\lib\JITIDL\ChakraJIT.idl
9>ChakraJIT.idl
9>64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\shared\wtypes.idl
9>wtypes.idl
9>64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\shared\wtypesbase.idl
1>SCACorePch.cpp
1>C:\Programs\vcpkg\buildtrees\chakracore\x64-windows-rel\x64-windows\lib\Common\Core\EtwTraceCore.h(81,10): fatal error C1083: Cannot open include file: 'Microsoft-Scripting-Chakra-InstrumentationEvents.h': No such file or directory
9>wtypesbase.idl
9>64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\shared\basetsd.h
9>basetsd.h
9>64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\shared\guiddef.h
```

**Comment by ppenzin** [comment] 2023-06-14 05:16
For some reason I've seen this before, I need to take a look one more time.

**Comment by fatcerberus** [comment] 2023-06-15 02:24
> For some reason I've seen this before

That would be my issue: https://github.com/chakra-core/ChakraCore/issues/6875 :wink:

@VitaliyMubarakov Just hit Build (*not* Rebuild) a second time, it should work then.

**Comment by rhuanjl** [comment] 2024-04-17 21:27
Closing as duplicate of #6875

**Closed as completed by rhuanjl** 2024-04-17 21:27 UTC
