### ISSUE TITLE
arguments.callee can't get the correct result

### ISSUE THREAD

**Issue by YiWen-y** [chakra-core/ChakraCore#6814] opened 2022-05-14 08:22 UTC
###### Version

chakra-1.11.24.0

###### Test case 

```js
var foo = function() {
    var me = arguments.callee;
    print(me.name);
}
foo();

```

###### Command 

    /root/.jsvu/ch Testcase.js

###### Output

```

```

###### Expected result

```
foo
```

###### Description

`callee` is a property of the `arguments` object. It can be used to refer to the currently executing function inside the function body of that function.But when executing this test case, chakra simply return nothing.

**Comment by pleath** [comment] 2022-05-16 18:28
This seems to be fixed in master. Note that the bug doesn't have to do with the arguments object. The behavior is the same if the test calls print(foo.name) instead of calling foo(). The behavior is correct, though, if the function expression has a name, as in, "var foo = function foo() {...", or if it uses a declaration statement, like "function foo() {...". The problem is that 1.11 doesn't initialize the name property in a case like "var foo = function() {...".

**Closed as completed** 2022-05-20 01:53 UTC
