### ISSUE TITLE
[Build]: When did ChakraCore start supporting compilation for ARM on Linux?

### ISSUE THREAD

**Issue by smithjiang** [chakra-core/ChakraCore#6997] opened 2024-07-05 00:57 UTC
### Operating System

jp master

### Compiler

jp master

### ChakraCore Version

jp master

### Compiler output

```shell
When did ChakraCore start supporting compilation for ARM on Linux?
```

### Additional Context

When did ChakraCore start supporting compilation for ARM on Linux?

**Comment by ppenzin** [comment] 2024-07-06 05:01
Duplicate of #6468, #6335

**Comment by ppenzin** [comment] 2024-07-06 05:02
(now with correct status)

**Closed as not planned by ppenzin** 2024-07-06 05:02 UTC
Labels: Duplicate, Feature Request
